[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["F", "E", "W", "I", "UP", "S", "B", "T20", "RUF"]
ignore = ["E501", "B904", "B007", "S308", "S113", "S314"]

[tool.ruff.isort]
known-first-party = ["pyscaffold"]

[tool.ruff.per-file-ignores]
"test_*.py" = ["S101", "S106"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = "tests"

[tool.coverage.run]
omit = [
  "./build/",
  "./tests/*",
  "./venv/*"
]
